[project]
name = 'genius'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.genius]
path = 'contracts/genius.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
